testname: webMUSHRA
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: diff codec
    - 
      - random
      - type: mushra
        id: 0
        name: MUSHRA
        content: 
        enableLooping: true
        reference: configs/resources/diffCodec_2ch/s1-M/1_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/diffCodec_2ch/s1-M/1_diff_1.wav
            C2: configs/resources/diffCodec_2ch/s1-M/1_diff_3.wav
            C3: configs/resources/diffCodec_2ch/s1-M/1_encodec_1_5.wav   
            C4: configs/resources/diffCodec_2ch/s1-M/1_encodec_3.wav   
            C5: configs/resources/diffCodec_2ch/s1-M/1_dac16_3kbps.wav       
      - type: mushra
        id: 1
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/diffCodec_2ch/s200-F/200_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/diffCodec_2ch/s200-F/200_diff_1.wav
            C2: configs/resources/diffCodec_2ch/s200-F/200_diff_3.wav
            C3: configs/resources/diffCodec_2ch/s200-F/200_encodec_1_5.wav   
            C4: configs/resources/diffCodec_2ch/s200-F/200_encodec_3.wav 
            C5: configs/resources/diffCodec_2ch/s200-F/200_dac16_3kbps.wav
    - type: finish
      name: Thank you
      content: Thank you for attending! <br/> Please put your name and press the [send results] button.
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: Your name
            name: name

