testname: webMUSHRA
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: <p>Thank you for participating in this listening test. This test will take about 20 minutes. </p> 
    - 
      - random
      - type: mushra
        id: trial_random_1
        name: MUSHRA
        content: 
        enableLooping: true
        reference: configs/resources/genc_samples/s1_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s1_syn20_bl.wav
            C2: configs/resources/genc_samples/s1_syn23.wav
            C3: configs/resources/genc_samples/s1_syn50_bl.wav
            C4: configs/resources/genc_samples/s1_qtz.wav           
      - type: mushra
        id: trial_random_3
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/s3_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s3_syn20_bl.wav
            C2: configs/resources/genc_samples/s3_syn23.wav
            C3: configs/resources/genc_samples/s3_syn50_bl.wav
            C4: configs/resources/genc_samples/s3_qtz.wav
      - type: mushra
        id: trial_random_4
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/s4_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s4_syn20_bl.wav
            C2: configs/resources/genc_samples/s4_syn23.wav
            C3: configs/resources/genc_samples/s4_syn50_bl.wav
            C4: configs/resources/genc_samples/s4_qtz.wav

      # - type: mushra
      #   id: trial_random_5
      #   name: MUSHRA
      #   content:
      #   enableLooping: true
      #   reference: configs/resources/genc_samples/s5_truth.wav
      #   createAnchor35: true
      #   createAnchor70: false
      #   stimuli:
      #       C1: configs/resources/genc_samples/s5_syn20_bl.wav
      #       C2: configs/resources/genc_samples/s5_syn23.wav
      #       C3: configs/resources/genc_samples/s5_syn50_bl.wav
      #       C4: configs/resources/genc_samples/s5_qtz.wav
      - type: mushra
        id: trial_random_6
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/s6_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s6_syn20_bl.wav
            C2: configs/resources/genc_samples/s6_syn23.wav
            C3: configs/resources/genc_samples/s6_syn50_bl.wav
            C4: configs/resources/genc_samples/s6_qtz.wav
      - type: mushra
        id: trial_random_7
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/s7_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s7_syn20_bl.wav
            C2: configs/resources/genc_samples/s7_syn23.wav
            C3: configs/resources/genc_samples/s7_syn50_bl.wav
            C4: configs/resources/genc_samples/s7_qtz.wav
      - type: mushra
        id: trial_random_9
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/s9_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s9_syn20_bl.wav
            C2: configs/resources/genc_samples/s9_syn23.wav
            C3: configs/resources/genc_samples/s9_syn50_bl.wav
            C4: configs/resources/genc_samples/s9_qtz.wav
      - type: mushra
        id: trial_random_16
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/s16_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s16_syn20_bl.wav
            C2: configs/resources/genc_samples/s16_syn23.wav
            C3: configs/resources/genc_samples/s16_syn50_bl.wav
            C4: configs/resources/genc_samples/s16_qtz.wav
      - type: mushra
        id: trial_random_lyra1
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/lyra1_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/lyra1_syn20_bl.wav
            C2: configs/resources/genc_samples/lyra1_syn23.wav
            C3: configs/resources/genc_samples/lyra1_syn50_bl.wav
            C4: configs/resources/genc_samples/lyra1_qtz.wav
            C5: configs/resources/genc_samples/lyra1.wav
      - type: mushra
        id: trial_random_lyra2
        name: MUSHRA
        content:
        enableLooping: true
        reference: configs/resources/genc_samples/lyra2_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/lyra2_syn20_bl.wav
            C2: configs/resources/genc_samples/lyra2_syn23.wav
            C3: configs/resources/genc_samples/lyra2_syn50_bl.wav
            C4: configs/resources/genc_samples/lyra2_qtz.wav
            C5: configs/resources/genc_samples/lyra2.wav


    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: Your name
            name: name

