testname: webMUSHRA
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Thank you for participating in this listening test. This test will take about 20 minutes. <br/> At the end of the test, please <b> put your name and click the [Submit Results] button </b> to make sure your results are successfully saved to the system.
    - 
      - random
      - type: mushra
        id: 0
        name: MUSHRA
        content: 
        enableLooping: true
        reference: configs/resources/genc_samples/s1/s1_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s1/s1_syn20_bl.wav
            C2: configs/resources/genc_samples/s1/s1_syn23.wav
            C3: configs/resources/genc_samples/s1/s1_full.wav
            C4: configs/resources/genc_samples/s1/s1_qtz.wav   
            C5: configs/resources/genc_samples/s1/s1_lyra.wav          
      - type: mushra
        id: 1
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s3/s3_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s3/s3_syn20_bl.wav
            C2: configs/resources/genc_samples/s3/s3_syn23.wav
            C3: configs/resources/genc_samples/s3/s3_full.wav
            C4: configs/resources/genc_samples/s3/s3_qtz.wav
            C5: configs/resources/genc_samples/s3/s3_lyra.wav
      - type: mushra
        id: 2
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s4/s4_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s4/s4_syn20_bl.wav
            C2: configs/resources/genc_samples/s4/s4_syn23.wav
            C3: configs/resources/genc_samples/s4/s4_full.wav
            C4: configs/resources/genc_samples/s4/s4_qtz.wav
            C5: configs/resources/genc_samples/s4/s4_lyra.wav

      - type: mushra
        id: 3
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s6/s6_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s6/s6_syn20_bl.wav
            C2: configs/resources/genc_samples/s6/s6_syn23.wav
            C3: configs/resources/genc_samples/s6/s6_full.wav
            C4: configs/resources/genc_samples/s6/s6_qtz.wav
            C5: configs/resources/genc_samples/s6/s6_lyra.wav
      - type: mushra
        id: 4
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s7/s7_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s7/s7_syn20_bl.wav
            C2: configs/resources/genc_samples/s7/s7_syn23.wav
            C3: configs/resources/genc_samples/s7/s7_full.wav
            C4: configs/resources/genc_samples/s7/s7_qtz.wav
            C5: configs/resources/genc_samples/s7/s7_lyra.wav
      - type: mushra
        id: 5
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s9/s9_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s9/s9_syn20_bl.wav
            C2: configs/resources/genc_samples/s9/s9_syn23.wav
            C3: configs/resources/genc_samples/s9/s9_full.wav
            C4: configs/resources/genc_samples/s9/s9_qtz.wav
            C5: configs/resources/genc_samples/s9/s9_lyra.wav
      - type: mushra
        id: 6
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s16/s16_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s16/s16_syn20_bl.wav
            C2: configs/resources/genc_samples/s16/s16_syn23.wav
            C3: configs/resources/genc_samples/s16/s16_full.wav
            C4: configs/resources/genc_samples/s16/s16_qtz.wav
            C5: configs/resources/genc_samples/s16/s16_lyra.wav

      - type: mushra
        id: 7
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s18/s18_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s18/s18_syn20_bl.wav
            C2: configs/resources/genc_samples/s18/s18_syn23.wav
            C3: configs/resources/genc_samples/s18/s18_full.wav
            C4: configs/resources/genc_samples/s18/s18_qtz.wav
            C5: configs/resources/genc_samples/s18/s18_lyra.wav
      - type: mushra
        id: 8
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s19/s19_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s19/s19_syn20_bl.wav
            C2: configs/resources/genc_samples/s19/s19_syn23.wav
            C3: configs/resources/genc_samples/s19/s19_full.wav
            C4: configs/resources/genc_samples/s19/s19_qtz.wav
            C5: configs/resources/genc_samples/s19/s19_lyra.wav
      - type: mushra
        id: 9
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/genc_samples/s22/s22_truth.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/genc_samples/s22/s22_syn20_bl.wav
            C2: configs/resources/genc_samples/s22/s22_syn23.wav
            C3: configs/resources/genc_samples/s22/s22_full.wav
            C4: configs/resources/genc_samples/s22/s22_qtz.wav
            C5: configs/resources/genc_samples/s22/s22_lyra.wav

    - type: finish
      name: Thank you
      content: Thank you for attending! <br/> Please put your name and press the [send results] button.
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: Your name
            name: name

