testname: webMUSHRA
testId: default_example
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Thank you for participating in this listening test. This test includes 10 sessions, and will take about 30 minutes. At each session, you are provided with a reference and 7 samples to compare, including a hidden reference and a 3.5kHz low-filter anchor (muffle sounding). <br/> Try to find the hidden reference and give it 100 points. Then rate the rest of the others always based on their comparison to the reference. <br/> To regularize, I suggest rating the muffle sounding anchor to a score around 10-30. <br/> At the end of the test, please <b> leave your name (or alias) and click the [Submit Results] button </b> to save your results.
    - 
      - random
      - type: mushra
        id: 0
        name: MUSHRA
        content: 
        enableLooping: true
        reference: configs/resources/2ch-15/s1-M/1_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s1-M/1_diff_1_5.wav
            C2: configs/resources/2ch-15/s1-M/1_diff_3.wav
            C3: configs/resources/2ch-15/s1-M/1_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s1-M/1_encodec_3.wav   
            C5: configs/resources/2ch-15/s1-M/1_dac16_3.wav       
      - type: mushra
        id: 1
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s200-F/200_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s200-F/200_diff_1_5.wav
            C2: configs/resources/2ch-15/s200-F/200_diff_3.wav
            C3: configs/resources/2ch-15/s200-F/200_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s200-F/200_encodec_3.wav 
            C5: configs/resources/2ch-15/s200-F/200_dac16_3.wav
      - type: mushra
        id: 2
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s300-F/300_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s300-F/300_diff_1_5.wav
            C2: configs/resources/2ch-15/s300-F/300_diff_3.wav
            C3: configs/resources/2ch-15/s300-F/300_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s300-F/300_encodec_3.wav 
            C5: configs/resources/2ch-15/s300-F/300_dac16_3.wav
      - type: mushra
        id: 3
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s430-F/430_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s430-F/430_diff_1_5.wav
            C2: configs/resources/2ch-15/s430-F/430_diff_3.wav
            C3: configs/resources/2ch-15/s430-F/430_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s430-F/430_encodec_3.wav 
            C5: configs/resources/2ch-15/s430-F/430_dac16_3.wav
      - type: mushra
        id: 4
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s510-F/510_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s510-F/510_diff_1_5.wav
            C2: configs/resources/2ch-15/s510-F/510_diff_3.wav
            C3: configs/resources/2ch-15/s510-F/510_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s510-F/510_encodec_3.wav 
            C5: configs/resources/2ch-15/s510-F/510_dac16_3.wav
      - type: mushra
        id: 5
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s900-M/900_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s900-M/900_diff_1_5.wav
            C2: configs/resources/2ch-15/s900-M/900_diff_3.wav
            C3: configs/resources/2ch-15/s900-M/900_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s900-M/900_encodec_3.wav 
            C5: configs/resources/2ch-15/s900-M/900_dac16_3.wav

      - type: mushra
        id: 6
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s1300-F/1300_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s1300-F/1300_diff_1_5.wav
            C2: configs/resources/2ch-15/s1300-F/1300_diff_3.wav
            C3: configs/resources/2ch-15/s1300-F/1300_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s1300-F/1300_encodec_3.wav 
            C5: configs/resources/2ch-15/s1300-F/1300_dac16_3.wav
      - type: mushra
        id: 7
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s1490-M/1490_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s1490-M/1490_diff_1_5.wav
            C2: configs/resources/2ch-15/s1490-M/1490_diff_3.wav
            C3: configs/resources/2ch-15/s1490-M/1490_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s1490-M/1490_encodec_3.wav
            C5: configs/resources/2ch-15/s1490-M/1490_dac16_3.wav 
      - type: mushra
        id: 8
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s1690-M/1690_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s1690-M/1690_diff_1_5.wav
            C2: configs/resources/2ch-15/s1690-M/1690_diff_3.wav
            C3: configs/resources/2ch-15/s1690-M/1690_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s1690-M/1690_encodec_3.wav 
            C5: configs/resources/2ch-15/s1690-M/1690_dac16_3.wav
      - type: mushra
        id: 9
        name: MUSHRA
        content: Please rate the samples only compared to the reference
        enableLooping: true
        reference: configs/resources/2ch-15/s2180-M/2180_x.wav
        createAnchor35: true
        createAnchor70: false
        stimuli:
            C1: configs/resources/2ch-15/s2180-M/2180_diff_1_5.wav
            C2: configs/resources/2ch-15/s2180-M/2180_diff_3.wav
            C3: configs/resources/2ch-15/s2180-M/2180_encodec_1_5.wav   
            C4: configs/resources/2ch-15/s2180-M/2180_encodec_3.wav 
            C5: configs/resources/2ch-15/s2180-M/2180_dac16_3.wav
    - type: finish
      name: Thank you
      content: Thank you for attending! <br/> Please put your name and press the [send results] button.
      showResults: true
      writeResults: true
      questionnaire:
          - type: text
            label: Your name
            name: name

